### ISSUE TITLE
Is there a version of this for Django 3.2?

### ISSUE THREAD

**Issue by simkimsia** [kursitet/django-last-seen#1]
And does it assume that redis is installed?

**Comment by Mihara** [comment]
> Is there a version of this for Django 3.2?

No. I hacked about for a while and then ended up adopting it into the main repository where it was used, because it was easier to get it to work at least a little this way. I will eventually be replacing it with something else entirely, so there's no point trying to release it.

Seriously, don't try to use this.

> And does it assume that redis is installed?

Not to my knowledge.
